#!/usr/bin/dh-exec
usr/bin/octave-[0-9]* /usr/bin
usr/bin/octave-cli* /usr/bin
usr/share/applications /usr/share
ARCH=$(uname -m)
usr/lib/${DEB_HOST_MULTIARCH}/octave/${DEB_VERSION_UPSTREAM}/exec/${DEB_HOST_MULTIARCH/-linux/-pc-linux}/* /usr/lib/${DEB_HOST_MULTIARCH}/octave/${DEB_VERSION_UPSTREAM}/exec/${DEB_HOST_MULTIARCH/-linux/-pc-linux}/
usr/lib/${DEB_HOST_MULTIARCH}/octave/${DEB_VERSION_UPSTREAM}/oct/* /usr/lib/${DEB_HOST_MULTIARCH}/octave/${DEB_VERSION_UPSTREAM}/oct/
