#!/bin/sh
#
# postinst script for the Debian GNU/Linux octave packages

set -e

#DEBHELPER#

rebuild_pkg_database () {
    octave --silent --no-history --no-init-file --no-window-system	\
	   --eval "pkg ('rebuild');"
}

case "$1" in
    configure)
	rebuild_pkg_database
	;;
    
    triggered)
        rebuild_pkg_database
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        ;;
esac

exit 0
